[package]
name = "_bevy"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "^0.13" }
winit = { version = "^0.29" }
