[package]
name = "_bevy"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
flume = "^0.11"
once_cell = "^1"

bevy = { version = "^0.13" }
raw-window-handle = { version = "^0.6" }
